global:
  scrape_interval: 30s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['127.0.0.1:9090']
    
- job_name: node-exporter
  static_configs:
  - targets: ['127.0.0.1:9100']

- job_name: grafana
  static_configs:
  - targets: ['127.0.0.1:3000']
